services:
  api:
    build: .
    container_name: sportify-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/sportify
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: sportify-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportify
      ENVIRONMENT: ${ENVIRONMENT:-development}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/sql/creation_database/001_federations.sql:/docker-entrypoint-initdb.d/001_federations.sql
      - ./scripts/sql/creation_database/002_people.sql:/docker-entrypoint-initdb.d/002_people.sql
      - ./scripts/sql/creation_database/003_teams.sql:/docker-entrypoint-initdb.d/003_teams.sql
      - ./scripts/sql/creation_database/004_sample_data.sql:/docker-entrypoint-initdb.d/004_sample_data.sql
      - ./scripts/sql/creation_database/validate_db.sql:/docker-entrypoint-initdb.d/validate_db.sql

volumes:
  pgdata: